---
- name: ensure default user custom gitconfig
  template:
    src: .my_gitconfig.j2
    dest: "{{ the_user_conf_dir }}/.my_gitconfig"
    owner: "{{ the_user }}"
    group: "{{ the_user_group }}"
    mode: 0600

- name: ensure default user gitconfig includes custom gitconfig
  blockinfile:
    dest: "{{ the_user_dir }}/.gitconfig"
    create: yes
    block: |
      [include]
        path = "{{ the_user_conf_dir }}/.my_gitconfig"
